### ISSUE TITLE
Request: Players lives don't auto increase based on groups

### ISSUE THREAD

**Issue by TheCodingGorilla** [okx-code/DeathBan#3]
```
Player has 3 lives.
Player is added to a group with lives set to 10.
Player now has 10 lives.
```

Could there also be a config option on a group by group basis to not increase lives?

```
  steward:
    permission: deathban.group.steward
    lives: 20
    time: 20m
    priority: 1000
    auto-increase: false
```

The rationale is to use groups to set the maximum lives the player can have without changing their current life count.
